#ifndef _HARDWARE_CONSTANTS_OVERRIDE_H
#define _HARDWARE_CONSTANTS_OVERRIDE_H

#include "u8g2sdl.h"

#undef DISPLAY_RATE
#define DISPLAY_RATE 0
#undef U8G2_INITIALIZATION
#define U8G2_INITIALIZATION U8G2_SDL u8g2(U8G2_R0);

#endif
